# GitHub pages defaults
pygments: true
safe:     true
lsi:      false

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  transliterated_header_ids: true

# these are actually not used yet, because GitHub haven't updated their Jekyll yet
defaults:
  - scope:
      path: "" # all files
    values:
      layout: default

permalink: pretty
